name: 自动签到续费麦块联机

on:
  schedule:
    - cron: '0 4 * * *' # 每天 4 点运行
  workflow_dispatch:

jobs:
  read-and-access:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          libnss3 \
          libxss1 \
          libasound2 \
          libx11-xcb1 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxrandr2 \
          libgbm1 \
          libgtk-3-0   
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
        rm -rf google-chrome-stable_current_amd64.deb
        cd minekuai
        python -m ensurepip --upgrade  # 确保 pip 已安装
        pip install -U pip
        pip install -r requirements.txt 
        
    - name: 签到续费麦块联机
      env:
        MK_TOKENS: ${{ secrets.MK_TOKENS }}
        GOOGLE_AISTUDIO: ${{ secrets.GOOGLE_AISTUDIO }}
      run: |
        #!/bin/bash
        set -e

        IFS=',' read -r -a entries <<< "$MK_TOKENS"

        for entry in "${entries[@]}"; do
          IFS=':' read -r user password <<< "$entry"
          cd minekuai
          echo "🔍 正在尝试签到..."
          python main.py --username $user --password $password --gapi "$GOOGLE_AISTUDIO"

        done
